### PR TITLE
Renamed classes

### PR DESCRIPTION
**Pull request by cshinn**
Replaced  "pf-timeline__\*" with "timeline-pf-\*" in all files

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Patternfly conventions also call for alphabetical ordering of css settings. I'll leave that up to you to conform or not (I'm not a particularly big fan of that convention).

**Review by jeff-phillips-18 — APPROVED** [review]
👍

**Review by dgutride — APPROVED** [review]

**Comment by dgutride** [comment]
@jeff-phillips-18  - are we good to merge this one?

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by cshinn** [comment]
FYI I just found and removed a comment that I had left in. Should be the same though

**Pull request merged**
