### PR TITLE
Updated class names and fixed marker bug

### PR DESCRIPTION
**Pull request by cshinn**
Prepends "pf-timeline__" to all class names, and addresses and issue in which the presence of the timestamp marker would cause it to hide itself in Firefox

Addresses #27

### CODE REVIEW

**Review by dgutride — APPROVED** [review]

**Comment by jeff-phillips-18** [comment]
A bit late but the Patternfly standard for css selectors would have your selectors be timeline-pf-*. And using __ will cause some projects to have eslint issues if trying to override.

**Comment by cshinn** [comment]
@jeff-phillips-18 I checked with @srambach for that name convention, and based it on this doc https://docs.google.com/document/d/1EQ5AK2op9gmEBbrKiVVmhcwgVRlFiL_M29o4pwalksA/edit

**Comment by jeff-phillips-18** [comment]
That is PF 4 guidelines and is not even public yet. Those guidelines are not yet in use and imo it would be better to remain under the current accepted conventions for consistency.

**Comment by cshinn** [comment]
@jeff-phillips-18 I'm happy to change it. Do you think it's worth an additional release?

**Comment by jeff-phillips-18** [comment]
Can we amend the current release quickly enough that changing it won't break anyone later?

**Pull request merged**
